# 所有实体的枚举
entity_enum = {
    1: "EXPERIENCE_ORB",  # 经验球
    2: "LEASH_HITCH",  # 拴绳结
    3: "PAINTING",  # 画
    4: "ARROW",  # 箭
    5: "SNOWBALL",  # 雪球
    6: "FIREBALL",  # 火球
    7: "SMALL_FIREBALL",  # 小火球
    9: "ENDER_PEARL",  # 末影珍珠
    10: "ENDER_SIGNAL",  # 末影信号
    11: "THROWN_EXP_BOTTLE",  # 扔出的经验瓶
    12: "ITEM_FRAME",  # 物品展示框
    13: "WITHER_SKULL",  # 凋零骷髅头
    14: "PRIMED_TNT",  # 点燃的TNT
    15: "FALLING_BLOCK",  # 掉落的方块
    16: "FIREWORK",  # 烟花火箭
    17: "MINECART_COMMAND",  # 命令方块矿车
    18: "BOAT",  # 船
    19: "MINECART",  # 普通矿车
    20: "MINECART_CHEST",  # 储物箱矿车
    21: "MINECART_FURNACE",  # 动力矿车
    22: "MINECART_TNT",  # TNT矿车
    23: "MINECART_HOPPER",  # 漏斗矿车
    24: "MINECART_MOB_SPAWNER",  # 刷怪笼矿车
    25: "CREEPER",  # 苦力怕
    26: "SKELETON",  # 骷髅
    27: "SPIDER",  # 蜘蛛
    28: "GIANT",  # 巨人
    29: "ZOMBIE",  # 僵尸
    30: "SLIME",  # 史莱姆
    31: "GHAST",  # 恶魂
    32: "PIG_ZOMBIE",  # 僵尸猪人
    33: "ENDERMAN",  # 末影人
    34: "CAVE_SPIDER",  # 洞穴蜘蛛
    35: "SILVERFISH",  # 蠹虫
    36: "BLAZE",  # 烈焰人
    37: "MAGMA_CUBE",  # 岩浆怪
    38: "ENDER_DRAGON",  # 末影龙
    39: "WITHER",  # 凋零兽
    40: "BAT",  # 蝙蝠
    41: "WITCH",  # 女巫
    42: "PIG",  # 猪
    43: "SHEEP",  # 羊
    44: "COW",  # 牛
    45: "CHICKEN",  # 鸡
    46: "SQUID",  # 鱿鱼
    47: "WOLF",  # 狼
    48: "MUSHROOM_COW",  # 哞菇（蘑菇牛）
    49: "SNOWMAN",  # 雪人
    50: "OCELOT",  # 豹猫（金钩豹）
    51: "IRON_GOLEM",  # 铁傀儡（铁巨人）
    52: "HORSE",  # 马（普通马）
    53: "VILLAGER",  # 村民（普通村民）
    54: "ENDER_CRYSTAL",  # 末影水晶
    55: "SPLASH_POTION",  # 飞溅药水（喷溅药水）
    56: "EGG",  # 鸡蛋
    57: "FISHING_HOOK",  # 鱼钩
}

# 所有材料的枚举
material_enum = {
    1: "AIR",  # 空气
    2: "STONE",  # 石头
    3: "GRASS",  # 草方块
    4: "DIRT",  # 泥土
    5: "COBBLESTONE",  # 圆石
    6: "WOOD",  # 木头
    7: "SAPLING",  # 树苗
    8: "BEDROCK",  # 基岩
    9: "WATER",  # 水（流动）
    10: "STATIONARY_WATER",  # 水（静止）
    11: "LAVA",  # 岩浆（流动）
    12: "STATIONARY_LAVA",  # 岩浆（静止）
    13: "SAND",  # 沙子
    14: "GRAVEL",  # 砂砾
    15: "GOLD_ORE",  # 金矿石
    16: "IRON_ORE",  # 铁矿石
    17: "COAL_ORE",  # 煤矿石
    18: "LOG",  # 木头原木
    19: "LEAVES",  # 树叶
    20: "SPONGE",  # 海绵
    21: "GLASS",  # 玻璃
    22: "LAPIS_ORE",  # 青金石矿石
    23: "LAPIS_BLOCK",  # 青金石块
    24: "DISPENSER",  # 发射器
    25: "SANDSTONE",  # 沙石
    26: "NOTE_BLOCK",  # 木板响石
    27: "BED_BLOCK",  # 床方块
    28: "POWERED_RAIL",  # 动力铁轨
    29: "DETECTOR_RAIL",  # 检测铁轨
    30: "PISTON_STICKY_BASE",  # 粘性活塞
    31: "WEB",  # 蜘蛛网
    32: "LONG_GRASS",  # 长草
    33: "DEAD_BUSH",  # 烧焦的灌木丛
    34: "PISTON_BASE",  # 活塞底座
    35: "PISTON_EXTENSION",  # 活塞臂
    36: "WOOL",  # 羊毛
    37: "PISTON_MOVING_PIECE",  # 移动的活塞臂
    38: "YELLOW_FLOWER",  # 金黄色的花
    39: "RED_ROSE",  # 红玫瑰
    40: "BROWN_MUSHROOM",  # 棕色蘑菇
    41: "RED_MUSHROOM",  # 红色蘑菇
    42: "GOLD_BLOCK",  # 金块
    43: "IRON_BLOCK",  # 铁块
    44: "DOUBLE_STEP",  # 双台阶
    45: "STEP",  # 台阶
    46: "BRICK",  # 砖块
    47: "TNT",  # TNT
    48: "BOOKSHELF",  # 书架
    49: "MOSSY_COBBLESTONE",  # 苔藓圆石
    50: "OBSIDIAN",  # 黑曜石
    51: "TORCH",  # 火把
    52: "FIRE",  # 火焰
    53: "MOB_SPAWNER",  # 刷怪笼
    54: "WOOD_STAIRS",  # 木质楼梯
    55: "CHEST",  # 木箱子
    56: "REDSTONE_WIRE",  # 红石线路
    57: "DIAMOND_ORE",  # 钻石矿石
    58: "DIAMOND_BLOCK",  # 钻石块
    59: "WORKBENCH",  # 工作台
    60: "CROPS",  # 农作物方块（小麦种子、西瓜种子、南瓜种子、甘蔗、胡萝卜、马铃薯）
    61: "SOIL",  # 耕地方块（需要种植农作物）
    62: "FURNACE",  # 熔炉（未点燃）
    63: "BURNING_FURNACE",  # 熔炉（点燃状态）
    64: "SIGN_POST",  # 支撑物（告示牌）
    65: "WOODEN_DOOR",  # 木门（下半部分）
    66: "LADDER",  # 梯子方块
    67: "RAILS",  # 铁轨方块（直线、弯曲、上升、下降）
    68: "COBBLESTONE_STAIRS",  # 圆石楼梯方块
    69: "WALL_SIGN",  # 墙上的告示牌方块
    70: "LEVER",  # 电门方块
    71: "STONE_PLATE",  # 压力板（轻质、重质）
    72: "IRON_DOOR_BLOCK",  # 铁门（下半部分）
    73: "WOOD_PLATE",  # 木质压力板（轻质、重质）
    74: "REDSTONE_ORE",  # 红石矿石（未点亮）
    75: "GLOWING_REDSTONE_ORE",  # 红石矿石（点亮状态）
    76: "REDSTONE_TORCH_OFF",  # 红石火把（未点亮）
    77: "REDSTONE_TORCH_ON",  # 红石火把（点亮状态）
    78: "STONE_BUTTON",  # 石质按钮方块
    79: "SNOW",  # 雪块方块（积雪层）
    80: "ICE",  # 冰块方块（透明、不透明）
    81: "SNOW_BLOCK",  # 雪块方块（整个方块）
    82: "CACTUS",  # 仙人掌方块（可以造成伤害）
    83: "CLAY",  # 黏土方块
    84: "SUGAR_CANE_BLOCK",  # 甘蔗方块（可以种植在耕地上）
    85: "JUKEBOX",  # 唱片机方块
    86: "FENCE",  # 木栅栏方块
    87: "PUMPKIN",  # 南瓜方块（可以雕刻成灯笼）
    88: "NETHERRACK",  # 地狱岩方块
    89: "SOUL_SAND",  # 幽灵沙方块（行走速度减缓）
    90: "GLOWSTONE",  # 萤石方块（发光）
    91: "PORTAL",  # 末地传送门方块（需要点亮）
    92: "JACK_O_LANTERN",  # 南瓜灯笼方块（发光）
    93: "CAKE_BLOCK",  # 蛋糕方块（可以食用）
    94: "DIODE_BLOCK_OFF",  # 红石中继器方块（未激活状态）
    95: "DIODE_BLOCK_ON",  # 红石中继器方块（激活状态）
    96: "LOCKED_CHEST",  # 锁定箱子方块
    97: "STAINED_GLASS",  # 染色玻璃方块
    98: "TRAP_DOOR",  # 活板门
    99: "MONSTER_EGGS",  # 虫蛋岩
    100: "SMOOTH_BRICK",  # 平滑石头
    101: "HUGE_MUSHROOM_1",  # 大型蘑菇
    102: "HUGE_MUSHROOM_2",  # 大型蘑菇
    103: "IRON_FENCE",  # 铁栏杆
    104: "THIN_GLASS",  # 薄玻璃
    105: "MELON_BLOCK",  # 西瓜
    106: "PUMPKIN_STEM",  # 南瓜梗
    107: "MELON_STEM",  # 西瓜梗
    108: "VINE",  # 藤蔓
    109: "FENCE_GATE",  # 栅栏门
    110: "BRICK_STAIRS",  # 砖楼梯
    111: "SMOOTH_STAIRS",  # 平滑楼梯
    112: "MYCEL",  # 菌丝
    113: "WATER_LILY",  # 荷叶
    114: "NETHER_BRICK",  # 地狱砖
    115: "NETHER_FENCE",  # 地狱栅栏
    116: "NETHER_BRICK_STAIRS",  # 地狱砖楼梯
    117: "NETHER_WARTS",  # 地狱裂草
    118: "ENCHANTMENT_TABLE",  # 附魔台
    119: "BREWING_STAND",  # 酿造台
    120: "CAULDRON",  # 长釜
    121: "ENDER_PORTAL",  # 末地传送门
    122: "ENDER_PORTAL_FRAME",  # 末地传送门框架
    123: "ENDER_STONE",  # 末地石
    124: "DRAGON_EGG",  # 龙蛋
    125: "REDSTONE_LAMP_OFF",  # 关闭的红石灯
    126: "REDSTONE_LAMP_ON",  # 打开的红石灯
    127: "WOOD_DOUBLE_STEP",  # 木制双半砖
    128: "WOOD_STEP",  # 木制半砖
    129: "COCOA",  # 可可果
    130: "SANDSTONE_STAIRS",  # 沙石阶梯
    131: "EMERALD_ORE",  # 绿宝石矿石
    132: "ENDER_CHEST",  # 末影箱
    133: "TRIPWIRE_HOOK",  # 绊线钩
    134: "TRIPWIRE",  # 绊线
    135: "EMERALD_BLOCK",  # 绿宝石方块
    136: "SPRUCE_WOOD_STAIRS",  # 云杉木阶梯
    137: "BIRCH_WOOD_STAIRS",  # 桦木阶梯
    138: "JUNGLE_WOOD_STAIRS",  # 丛林木阶梯
    139: "COMMAND",  # 命令方块
    140: "BEACON",  # 信标
    141: "COBBLE_WALL",  # 圆石墙
    142: "FLOWER_POT",  # 花盆
    143: "CARROT",  # 胡萝卜
    144: "POTATO",  # 马铃薯
    145: "WOOD_BUTTON",  # 木质按钮
    146: "SKULL",  # 骷髅头颅
    147: "ANVIL",  # 铁砧
    148: "TRAPPED_CHEST",  # 陷阱箱
    149: "GOLD_PLATE",  # 金质压力板
    150: "IRON_PLATE",  # 铁质压力板
    151: "REDSTONE_COMPARATOR_OFF",  # 关闭的红石比较器
    152: "REDSTONE_COMPARATOR_ON",  # 打开的红石比较器
    153: "DAYLIGHT_DETECTOR",  # 日光传感器
    154: "REDSTONE_BLOCK",  # 红石块
    155: "QUARTZ_ORE",  # 石英矿石
    156: "HOPPER",  # 漏斗
    157: "QUARTZ_BLOCK",  # 石英块
    158: "QUARTZ_STAIRS",  # 石英阶梯
    159: "ACTIVATOR_RAIL",  # 激活铁轨
    160: "DROPPER",  # 投掷器
    161: "STAINED_CLAY",  # 染色粘土块
    162: "STAINED_GLASS_PANE",  # 染色玻璃板
    163: "LEAVES_2",  # 丛林树叶
    164: "LOG_2",  # 丛林树木原木
    165: "ACACIA_STAIRS",  # 金合欢木阶梯
    166: "DARK_OAK_STAIRS",  # 黑橡木阶梯
    167: "HAY_BLOCK",  # 干草块
    168: "CARPET",  # 地毯
    169: "HARD_CLAY",  # 硬化粘土块
    170: "COAL_BLOCK",  # 煤炭块
    171: "PACKED_ICE",  # 压缩冰块
    172: "DOUBLE_PLANT",  # 高草丛
    173: "IRON_SPADE",  # 铁锹
    174: "IRON_PICKAXE",  # 铁镐
    175: "IRON_AXE",  # 铁斧
    176: "FLINT_AND_STEEL",  # 打火石
    177: "APPLE",  # 苹果
    178: "BOW",  # 弓
    179: "ARROW",  # 箭
    180: "COAL",  # 煤炭
    181: "DIAMOND",  # 钻石
    182: "IRON_INGOT",  # 铁锭
    183: "GOLD_INGOT",  # 金锭
    184: "IRON_SWORD",  # 铁剑
    185: "WOOD_SWORD",  # 木剑
    186: "WOOD_SPADE",  # 木锹
    187: "WOOD_PICKAXE",  # 木镐
    188: "WOOD_AXE",  # 木斧
    189: "STONE_SWORD",  # 石剑
    190: "STONE_SPADE",  # 石锹
    191: "STONE_PICKAXE",  # 石镐
    192: "STONE_AXE",  # 石斧
    193: "DIAMOND_SWORD",  # 钻石剑
    194: "DIAMOND_SPADE",  # 钻石锹
    195: "DIAMOND_PICKAXE",  # 钻石镐
    196: "DIAMOND_AXE",  # 钻石斧
    197: "STICK",  # 木棍
    198: "BOWL",  # 碗
    199: "MUSHROOM_SOUP",  # 蘑菇汤
    200: "GOLD_SWORD",  # 金剑
    201: "GOLD_SPADE",  # 金锹
    202: "GOLD_PICKAXE",  # 金镐
    203: "GOLD_AXE",  # 金斧
    204: "STRING",  # 线
    205: "FEATHER",  # 羽毛
    206: "SULPHUR",  # 硫磺
    207: "WOOD_HOE",  # 木锄
    208: "STONE_HOE",  # 石锄
    209: "IRON_HOE",  # 铁锄
    210: "DIAMOND_HOE",  # 钻石锄
    211: "GOLD_HOE",  # 金锄
    212: "SEEDS",  # 小麦种子
    213: "WHEAT",  # 小麦
    214: "BREAD",  # 面包
    215: "LEATHER_HELMET",  # 皮革帽子
    216: "LEATHER_CHESTPLATE",  # 皮革外套
    217: "LEATHER_LEGGINGS",  # 皮革裤子
    218: "LEATHER_BOOTS",  # 皮革靴子
    219: "CHAINMAIL_HELMET",  # 锁链头盔
    220: "CHAINMAIL_CHESTPLATE",  # 锁链胸甲
    221: "CHAINMAIL_LEGGINGS",  # 锁链护腿
    222: "CHAINMAIL_BOOTS",  # 锁链靴子
    223: "IRON_HELMET",  # 铁头盔
    224: "IRON_CHESTPLATE",  # 铁胸甲
    225: "IRON_LEGGINGS",  # 铁护腿
    226: "IRON_BOOTS",  # 铁靴子
    227: "DIAMOND_HELMET",  # 钻石头盔
    228: "DIAMOND_CHESTPLATE",  # 钻石胸甲
    229: "DIAMOND_LEGGINGS",  # 钻石护腿
    230: "DIAMOND_BOOTS",  # 钻石靴子
    231: "GOLD_HELMET",  # 金头盔
    232: "GOLD_CHESTPLATE",  # 金胸甲
    233: "GOLD_LEGGINGS",  # 金护腿
    234: "GOLD_BOOTS",  # 金靴子
    235: "FLINT",  # 打火石
    236: "PORK",  # 生猪肉
    237: "GRILLED_PORK",  # 熟猪肉
    238: "PAINTING",  # 画
    239: "GOLDEN_APPLE",  # 金苹果
    240: "SIGN",  # 告示牌
    241: "WOOD_DOOR",  # 木门
    242: "BUCKET",  # 桶
    243: "WATER_BUCKET",  # 水桶
    244: "LAVA_BUCKET",  # 岩浆桶
    245: "MINECART",  # 矿车
    246: "SADDLE",  # 鞍
    247: "IRON_DOOR",  # 铁门
    248: "REDSTONE",  # 红石粉
    249: "SNOW_BALL",  # 雪球
    250: "BOAT",  # 小船
    251: "LEATHER",  # 皮革
    252: "MILK_BUCKET",  # 牛奶桶
    253: "CLAY_BRICK",  # 粘土砖
    254: "CLAY_BALL",  # 粘土球
    255: "SUGAR_CANE",  # 甘蔗
    256: "PAPER",  # 纸张
    257: "BOOK",  # 书
    258: "SLIME_BALL",  # 史莱姆球
    259: "STORAGE_MINECART",  # 存储矿车
    260: "POWERED_MINECART",  # 动力矿车
    261: "EGG",  # 鸡蛋
    262: "COMPASS",  # 指南针
    263: "FISHING_ROD",  # 钓鱼竿
    264: "WATCH",  # 手表
    265: "GLOWSTONE_DUST",  # 萤石粉
    266: "RAW_FISH",  # 生鱼片
    267: "COOKED_FISH",  # 熟鱼片
    268: "INK_SACK",  # 墨囊/墨水袋/染料/黑色染料
    269: "BONE",  # 骨头
    270: "SUGAR",  # 糖
    271: "CAKE",  # 蛋糕
    272: "BED",  # 床
    273: "DIODE",  # 重复性红石电路/红石中继器/红石延迟器
    274: "COOKIE",  # 曲奇饼干/小甜饼
    275: "MAP",  # 地图
    276: "SHEARS",  # 剪刀
    277: "MELON",  # 西瓜
    278: "PUMPKIN_SEEDS",  # 南瓜种子
    279: "MELON_SEEDS",  # 西瓜种子
    280: "RAW_BEEF",  # 生牛肉
    281: "COOKED_BEEF",  # 牛排
    282: "RAW_CHICKEN",  # 生鸡肉
    283: "COOKED_CHICKEN",  # 熟鸡肉
    284: "ROTTEN_FLESH",  # 腐肉
    285: "ENDER_PEARL",  # 末影珍珠
    286: "BLAZE_ROD",  # 火焰棒
    287: "GHAST_TEAR",  # 恶魂之泪
    288: "GOLD_NUGGET",  # 金粒
    289: "NETHER_STALK",  # 地狱菌棒
    290: "POTION",  # 药水
    291: "GLASS_BOTTLE",  # 玻璃瓶
    292: "SPIDER_EYE",  # 蜘蛛眼
    293: "FERMENTED_SPIDER_EYE",  # 发酵蜘蛛眼
    294: "BLAZE_POWDER",  # 烈焰粉
    295: "MAGMA_CREAM",  # 岩浆膏
    296: "BREWING_STAND_ITEM",  # 酿造台
    297: "CAULDRON_ITEM",  # 大锅
    298: "EYE_OF_ENDER",  # 末影之眼
    299: "SPECKLED_MELON",  # 闪烁的西瓜
    300: "MONSTER_EGG",  # 刷怪蛋
    301: "EXP_BOTTLE",  # 经验瓶
    302: "FIREBALL",  # 火球
    303: "BOOK_AND_QUILL",  # 书和羽毛笔
    304: "WRITTEN_BOOK",  # 写好的书
    305: "EMERALD",  # 绿宝石
    306: "ITEM_FRAME",  # 物品展示框
    307: "FLOWER_POT_ITEM",  # 盆栽
    308: "CARROT_ITEM",  # 胡萝卜
    309: "POTATO_ITEM",  # 马铃薯
    310: "BAKED_POTATO",  # 烤马铃薯
    311: "POISONOUS_POTATO",  # 有毒马铃薯
    312: "EMPTY_MAP",  # 空地图
    313: "GOLDEN_CARROT",  # 金色胡萝卜
    314: "SKULL_ITEM",  # 骷髅头颅
    315: "CARROT_STICK",  # 胡萝卜钓竿
    316: "NETHER_STAR",  # 下界之星
    317: "PUMPKIN_PIE",  # 南瓜派
    318: "FIREWORK",  # 烟花火箭
    319: "FIREWORK_CHARGE",  # 烟花星球
    320: "ENCHANTED_BOOK",  # 附魔之书
    321: "REDSTONE_COMPARATOR",  # 红石比较器
    322: "NETHER_BRICK_ITEM",  # 下界砖块
    323: "QUARTZ",  # 下界石英
    324: "EXPLOSIVE_MINECART",  # 炸药矿车
    325: "HOPPER_MINECART",  # 漏斗矿车
    326: "IRON_BARDING",  # 铁马甲
    327: "GOLD_BARDING",  # 金马甲
    328: "DIAMOND_BARDING",  # 钻石马甲
    329: "LEASH",  # 拴绳
    330: "NAME_TAG",  # 名称标签
    331: "COMMAND_MINECART",  # 命令方块矿车
    332: "GOLD_RECORD",  # 黄金唱片
    333: "GREEN_RECORD",  # 绿色唱片
    334: "RECORD_3",  # 第三张唱片
    335: "RECORD_4",  # 第四张唱片
    336: "RECORD_5",  # 第五张唱片
    337: "RECORD_6",  # 第六张唱片
    338: "RECORD_7",  # 第七张唱片
    339: "RECORD_8",  # 第八张唱片
    340: "RECORD_9",  # 第九张唱片
    341: "RECORD_10",  # 第十张唱片
    342: "RECORD_11",  # 第十一张唱片
    343: "RECORD_12",  # 第十二张唱片
}

# 所有的附魔信息
enchantment_enum = {
    1: "PROTECTION_ENVIRONMENTAL",  # 环境保护
    2: "PROTECTION_FIRE",  # 火焰保护
    3: "PROTECTION_FALL",  # 跌落保护
    4: "PROTECTION_EXPLOSIONS",  # 爆炸保护
    5: "PROTECTION_PROJECTILE",  # 弹射物保护
    6: "OXYGEN",  # 氧气
    7: "WATER_WORKER",  # 水中速掘
    8: "THORNS",  # 荆棘
    9: "DAMAGE_ALL",  # 锋利
    10: "DAMAGE_UNDEAD",  # 亡灵杀手
    11: "DAMAGE_ARTHROPODS",  # 节肢杀手
    12: "KNOCKBACK",  # 击退
    13: "FIRE_ASPECT",  # 火焰附加
    14: "LOOT_BONUS_MOBS",  # 掠夺
    15: "DIG_SPEED",  # 效率
    16: "SILK_TOUCH",  # 精准采集
    17: "DURABILITY",  # 耐久
    18: "LOOT_BONUS_BLOCKS",  # 时运
    19: "ARROW_DAMAGE",  # 力量
    20: "ARROW_KNOCKBACK",  # 冲击
    21: "ARROW_FIRE",  # 火矢
    22: "ARROW_INFINITE",  # 无限
    23: "LUCK",  # 幸运
    24: "LURE",  # 饵钓
}
